/*
 * CodeGenAndTransformerAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.apimatic.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ValidateAnAPIDescriptionResponse 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5195195367878284535L;
    private List<Object> errors;
    private List<Object> warnings;
    private List<Object> messages;
    private boolean success;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Errors")
    public List<Object> getErrors ( ) { 
        return this.errors;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Errors")
    public void setErrors (List<Object> value) { 
        this.errors = value;
        notifyObservers(this.errors);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Warnings")
    public List<Object> getWarnings ( ) { 
        return this.warnings;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Warnings")
    public void setWarnings (List<Object> value) { 
        this.warnings = value;
        notifyObservers(this.warnings);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Messages")
    public List<Object> getMessages ( ) { 
        return this.messages;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Messages")
    public void setMessages (List<Object> value) { 
        this.messages = value;
        notifyObservers(this.messages);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Success")
    public boolean getSuccess ( ) { 
        return this.success;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Success")
    public void setSuccess (boolean value) { 
        this.success = value;
        notifyObservers(this.success);
    }
 
}
 